backend:
  name: github
  repo: eoinom/AllAboutErik

media_folder: "static/uploads"
public_folder: "/uploads"
# media_folder: "src/assets/uploads"
# public_folder: "/assets/static"

collections:
  - name: "posts"
    label: "Post"
    folder: "src/data/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "roots&youth videos"
    label: "Roots & Youth Video"
    folder: "src/data/roots&youth"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}      
      - {label: "Length", name: "length", widget: "datetime", dateFormat: false, timeFormat: "hh:mm:ss"}
      - {label: "Caption", name: "caption", widget: "markdown"}
  - name: "nav menu items"
    label: "Nav Menu Item"
    folder: "src/data/navMenu"
    create: true
    slug: "{{slug}}"
    identifier_field: text
    fields:
      - {label: "Text", name: "text", widget: "string"}
      - {label: "Local url target", name: "to", widget: "string"}      
      - {label: "List order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}      
      - {label: "Contains sub-menu?", name: "hasSubMenu", widget: "boolean"}      
      - {label: "Image", name: "img", widget: "image", required: false}  
      - {label: "Verb", name: "verb", widget: "string", required: false}  
      - {label: "Title", name: "title", widget: "string", required: false}  
      - label: "Sub Page"
        name: "subPages"
        widget: "list"
        required: false
        fields: 
          - {label: "Subpage Text", name: "subPageText", widget: "string"}  
          - {label: "Subpage url targt", name: "subPageTo", widget: "string"}
  - name: "homePg" 
    label: "Home Page"
    folder: "src/data/homePg"
    create: true
    slug: "{{slug}}"
    identifier_field: pageTitle
    fields:
      - {label: "Page Title", name: "pageTitle", widget: "image"}  
      - {label: "Heading Image", name: "headingImg", widget: "image"}  
      - {label: 'Main text', name: 'body', widget: 'markdown'}  
      - {label: 'Credit text', name: 'creditText', widget: 'string', required: false}
      - label: "Slides"
        name: "slides"
        widget: "list"
        fields: 
          - {label: "Image", name: "img", widget: "image"} 
          - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
          - {label: "Opacity (%)", name: "opacity", widget: "number", valueType: "int", min: 0, max: 100}
          - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0, max: 60}
          - {label: "Scale from", name: "scaleFrom", widget: "number", valueType: "float", min: 1, max: 2}
          - {label: "Scale to", name: "scaleTo", widget: "number", valueType: "float", min: 1, max: 2}
          - label: "Pan start from"
            name: "panStart"
            widget: "select"
            options: ["top-left", "top", "top-right", "left", "centre", "right", "bottom-left", "bottom", "bottom-right"]