backend:
  name: github
  repo: eoinom/AllAboutErik

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "src/data/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "roots&youth videos"
    label: "Roots & Youth Video"
    folder: "src/data/roots&youth"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}      
      - {label: "Length", name: "length", widget: "datetime", dateFormat: false, timeFormat: "hh:mm:ss"}
      - {label: "Caption", name: "caption", widget: "markdown"}