backend:
  name: github
  repo: eoinom/AllAboutErik

media_folder: "static/uploads"
public_folder: "/uploads"
# media_folder: "src/assets/uploads"
# public_folder: "/assets/static"

collections:
  - name: "posts"
    label: "Post"
    folder: "src/data/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "roots&youth videos"
    label: "Roots & Youth Video"
    folder: "src/data/roots&youth"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}      
      - {label: "Length", name: "length", widget: "datetime", dateFormat: false, timeFormat: "hh:mm:ss"}
      - {label: "Caption", name: "caption", widget: "markdown"}
  - name: "nav menu items"
    label: "Nav Menu Item"
    folder: "src/data/navMenu"
    create: true
    slug: "{{slug}}"
    identifier_field: text
    fields:
      - {label: "Text", name: "text", widget: "string"}
      - {label: "To", name: "to", widget: "string"}      
      - {label: "OrderNo", name: "orderNo", widget: "number", valueType: "int", min: 1}      
      - {label: "HasSubMenu", name: "hasSubMenu", widget: "boolean"}      
      - {label: "Img", name: "img", widget: "image", required: false}  
      - {label: "Verb", name: "verb", widget: "string", required: false}  
      - {label: "Title", name: "title", widget: "string", required: false}  
      - label: "SubPage"
        name: "subPages"
        widget: "list"
        required: false
        fields: 
          - {label: "SubPageText", name: "subPageText", widget: "string"}  
          - {label: "SubPageTo", name: "subPageTo", widget: "string"}