backend:
  name: github
  repo: eoinom/AllAboutErik

media_folder: "static/uploads"
public_folder: "/uploads"
# media_folder: "src/assets/uploads"
# public_folder: "/assets/static"
media_library:
  name: cloudinary
  config:
    cloud_name: all-about-erik
    api_key: 884234271445431
    multiple: true

collections:
  - label: "Nav Menu Items"
    name: "nav menu items"
    folder: "src/data/navMenuItems"
    create: true
    slug: "{{slug}}"
    identifier_field: text
    fields:
      - {label: "Text", name: "text", widget: "string"}
      - {label: "Local url target", name: "to", widget: "string"}      
      - {label: "List order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}      
      - {label: "Contains sub-menu?", name: "hasSubMenu", widget: "boolean"}      
      - {label: "Image", name: "img", widget: "image", required: false}  
      - {label: "Verb", name: "verb", widget: "string", required: false}  
      - {label: "Title", name: "title", widget: "string", required: false}  
      - label: "Sub Page"
        name: "subPages"
        widget: "list"
        required: false
        fields: 
          - {label: "Subpage Text", name: "subPageText", widget: "string"}  
          - {label: "Subpage url targt", name: "subPageTo", widget: "string"}


  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homePg" 
        file: "src/data/pages/homePg.md"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}  
          - {label: "Heading Image", name: "headingImg", widget: "image"}  
          - {label: 'Main text', name: 'body', widget: 'markdown'}  
          - {label: 'Credit text', name: 'creditText', widget: 'string', required: false}
          - {label: 'Background Audio', name: 'bgAudio', widget: 'file', required: false}
          - {label: 'Background Audio Duration', name: 'bgAudioDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade In Duration', name: 'bgAudioFadeInDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade Out Duration', name: 'bgAudioFadeOutDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - label: "Slides"
            name: "slides"
            widget: "list"
            fields: 
              - {label: "Image", name: "img", widget: "image"} 
              - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
              - {label: "Opacity (%)", name: "opacity", widget: "number", valueType: "int", min: 0, max: 100}
              - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0, max: 60}
              - {label: "Scale from", name: "scaleFrom", widget: "number", valueType: "float", min: 1, max: 2}
              - {label: "Scale to", name: "scaleTo", widget: "number", valueType: "float", min: 1, max: 2}
              - label: "Pan start from"
                name: "panStart"
                widget: "select"
                options: ["top-left", "top", "top-right", "left", "centre", "right", "bottom-left", "bottom", "bottom-right"]
                
      - label: "Roots & Youth"
        name: "roots&youth"
        file: "src/data/pages/roots-and-youth.md"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}  
          - {label: "Heading Image", name: "headingImg", widget: "image"}  
          - {label: 'Main text', name: 'body', widget: 'markdown', required: false} 
          - {label: 'Background Audio', name: 'bgAudio', widget: 'file', required: false}
          - {label: 'Background Audio Duration', name: 'bgAudioDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade In Duration', name: 'bgAudioFadeInDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade Out Duration', name: 'bgAudioFadeOutDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - label: "Slides"
            name: "slides"
            widget: "list"
            fields: 
              - {label: "Image", name: "img", widget: "image"} 
              - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
              - {label: "Opacity (%)", name: "opacity", widget: "number", valueType: "int", min: 0, max: 100, required: false}
          - {label: "Slide duration (secs)", name: "slideDuration", widget: "number", valueType: "float", min: 0, max: 60, required: false}
          - label: "Videos"
            name: "videos"
            widget: "list"
            fields: 
              - {label: 'Title', name: 'title', widget: 'string', required: false}
              - {label: 'Subtext', name: 'subText', widget: 'markdown', required: false}
              - {label: "Vimeo Url", name: "url", widget: "string"}
              - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}  
              - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
              - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0, required: false}          
          - label: "Full Video"
            name: "fullVideo"
            widget: "object"
            fields:
            - {label: 'Title', name: 'title', widget: 'string', required: false}
            - {label: "Text", name: "text", widget: "string"}
            - {label: "Video File", name: "file", widget: "file", required: false}
            - {label: "Video Url", name: "url", widget: "string", required: false}
            - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image", required: false}        
            - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0, required: false}
            
      - label: "Musical Journey - The Episodes"
        name: "the-episodes"
        file: "src/data/pages/musical-journey/the-episodes.md"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Header Background Image", name: "headerBgImg", widget: "image"}
          - {label: "Title Image", name: "titleImg", widget: "image"}
          - {label: 'Main text', name: 'body', widget: 'markdown', required: false} 
          - {label: 'Main image', name: 'mainImg', widget: 'image'}
          - {label: 'Background Audio', name: 'bgAudio', widget: 'file', required: false}
          - {label: 'Background Audio Duration', name: 'bgAudioDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade In Duration', name: 'bgAudioFadeInDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade Out Duration', name: 'bgAudioFadeOutDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - label: "Videos"
            name: "videos"
            widget: "list"
            fields: 
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Short Title', name: 'shortTitle', widget: 'string'}
              - {label: 'Subtext', name: 'subText', widget: 'markdown'}
              - {label: "Vimeo Url", name: "url", widget: "string"}
              - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}  
              - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
              - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0}

      - label: "Musical Journey - Musical Friends"
        name: "musical-friends"
        file: "src/data/pages/musical-journey/musical-friends.md"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Background Image", name: "backgroundImg", widget: "image"}
          - {label: "Title Image", name: "titleImg", widget: "image"}      
          - {label: 'Main text', name: 'body', widget: 'markdown', required: false}
          - {label: 'Background Audio', name: 'bgAudio', widget: 'file', required: false}
          - {label: 'Background Audio Duration', name: 'bgAudioDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade In Duration', name: 'bgAudioFadeInDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade Out Duration', name: 'bgAudioFadeOutDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - label: "Friends"
            name: "friends"
            widget: "list"
            fields: 
              - {label: 'Name / Title', name: 'name', widget: 'string'}
              - {label: 'Text', name: 'text', widget: 'markdown'}
              - {label: "Link (url)", name: "link", widget: "string"}
              - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
              - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}
              - {label: "Image Orientation", name: "imgOrientation", widget: "select", options: ["landscape", "portrait"]}
              - label: "Image Position"
                name: "imgPosition"
                widget: "select"
                options: ["top", "bottom", "left", "right"]

      - label: "Musical Journey - Musical Friends - Nadia Music"
        name: "nadia-music"
        file: "src/data/pages/musical-journey/nadia-music.md"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Title Text", name: "titleText", widget: "string"}
          - label: "Tracks"
            name: "tracks"
            widget: "list"
            fields: 
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: "Track Url", name: "url", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - label: "Image Position"
                name: "imgPosition"
                widget: "select"
                options: ["left", "right"]

      - label: "Musical Journey - Early Productions"
        name: "early-productions"
        file: "src/data/pages/musical-journey/early-productions.md"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Header Background Image", name: "headerBgImg", widget: "image"}
          - {label: "Title Image", name: "titleImg", widget: "image"}
          - {label: 'Main Text', name: 'body', widget: 'markdown', required: false} 
          - {label: 'Main image', name: 'mainImg', widget: 'image'} 
          - {label: 'Background Audio', name: 'bgAudio', widget: 'file', required: false}
          - {label: 'Background Audio Duration', name: 'bgAudioDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade In Duration', name: 'bgAudioFadeInDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade Out Duration', name: 'bgAudioFadeOutDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields: 
              - label: "Text Boxes"
                name: "textBoxes"
                widget: "list"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "markdown"}
              - label: "Productions"
                name: "productions"
                widget: "list"
                fields:
                  - {label: "Writer", name: "writer", widget: "string", required: false}
                  - {label: "Artist", name: "artist", widget: "string", required: false}
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Background Image", name: "bgImg", widget: "image", required: false}
                  - {label: "Background Image Position", name: "bgImgPos", widget: "select", options: ["top left", "top", "top right", "left", "center", "right", "bottom left", "bottom", "bottom right"], required: false}
                  - {label: "Background Color", name: "bgColor", widget: "string", required: false}
                  - {label: "Background Opacity", name: "bgOpacity", widget: "number", valueType: "float", min: 0, max: 1, required: false}
                  - label: "Tracks"
                    name: "tracks"
                    widget: "list"
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Track", name: "track", widget: "file"}
              - label: "Image Lightboxes"
                name: "imageLightboxes"
                widget: "list"
                required: false
                fields:
                  - {label: "Button Text", name: "buttonText", widget: "string"}
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Caption", name: "caption", widget: "string", required: false}

      - label: "Musical Journey - Discography"
        name: "discography"
        file: "src/data/pages/musical-journey/discography.md"
        fields:
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Title Image", name: "titleImg", widget: "image"}      
          - {label: 'Main Text', name: 'titleText', widget: 'markdown', required: false}
          - {label: 'Background Audio', name: 'bgAudio', widget: 'file', required: false}
          - {label: 'Background Audio Duration', name: 'bgAudioDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade In Duration', name: 'bgAudioFadeInDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - {label: 'Background Audio Fade Out Duration', name: 'bgAudioFadeOutDuration', widget: 'number', valueType: "float", min: 0, required: false}
          - label: "Background Images"
            name: "backgroundImages"
            widget: "list"
            fields:
              - {label: "Image", name: "img", widget: "image"}
              - {label: "Overlay Image", name: "imgOverlay", widget: "image", required: false}          
          - {label: 'Body text', name: 'body', widget: 'markdown'}
          - label: "Albums"
            name: "albums"
            widget: "list"
            fields: 
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Artist', name: 'artist', widget: 'string'}
              - {label: 'Text', name: 'text', widget: 'markdown'}
              - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}
              - {label: 'Track Listing', name: 'trackListing', widget: 'markdown'}
              - {label: "Label", name: "label", widget: "string", required: false}
              - {label: "Format", name: "format", widget: "string", required: false}
              - {label: "Country", name: "country", widget: "string", required: false}
              - {label: "Released", name: "released", widget: "string", required: false}
              - {label: "Style", name: "style", widget: "string", required: false}
              - {label: 'Credits', name: 'credits', widget: 'markdown'}

  - label: "Friends"
    name: "friends"
    folder: "src/data/pages/musical-journey/friends"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}  
      - {label: "Heading override", name: "heading", widget: "string", required: false}  
      - {label: "Background Image", name: "backgroundImg", widget: "image"}
      - {label: "Background Opacity (%)", name: "backgroundOpacity", widget: "number", valueType: "int", min: 0, max: 100}
      - {label: 'Main text', name: 'body', widget: 'markdown'}
      - label: "Media Items"
        name: "mediaItems"
        widget: "list"
        required: false
        fields:
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
          - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}
          - label: "Media type"
            name: "mediaType"
            widget: "select"
            options: ["images", "videos", "audio", "link"]
          - label: "Galleries"
            name: "galleries"
            widget: "list"
            types:    
              - label: "Image Gallery"
                name: "imageGallery"
                widget: "object"
                required: false
                fields:
                  - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
                  - {label: "Label", name: "label", widget: "string", required: false}    
                  - label: "Images"
                    name: "images"
                    widget: "list"
                    required: false
                    fields: 
                      - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
                      - {label: "Image", name: "img", widget: "image", valueType: "int"} 
                      - {label: "Caption", name: "caption", widget: "string", required: false}
              - label: "Video Gallery"
                name: "videoGallery"
                widget: "object"
                required: false
                fields:
                  - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
                  - {label: "Label", name: "label", widget: "string", required: false}    
                  - label: "Videos"
                    name: "videos"
                    widget: "list"
                    required: false
                    fields: 
                      - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
                      - {label: "Vimeo Url", name: "url", widget: "string"}
                      - {label: "Caption", name: "caption", widget: "string", required: false}
              - label: "Audio Gallery"
                name: "audioGallery"
                widget: "object"
                required: false
                fields:
                  - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
                  - {label: "Label", name: "label", widget: "string", required: false}    
                  - label: "Audio"
                    name: "audio"
                    widget: "list"
                    required: false
                    fields: 
                      - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
                      - {label: "Audio Url (Soundcloud)", name: "url", widget: "string"}
                      - {label: "Caption", name: "caption", widget: "string", required: false}
              - label: "Link"
                name: "link"
                widget: "object"
                required: false
                fields:
                  - {label: "link (url)", name: "url", widget: "string"}
                
          