backend:
  name: github
  repo: eoinom/AllAboutErik

media_folder: "static/uploads"
public_folder: "/uploads"
# media_folder: "src/assets/uploads"
# public_folder: "/assets/static"
media_library:
  name: cloudinary
  config:
    cloud_name: all-about-erik
    api_key: 884234271445431

collections:
  - name: "nav menu items"
    label: "Nav Menu Item"
    folder: "src/data/navMenu"
    create: true
    slug: "{{slug}}"
    identifier_field: text
    fields:
      - {label: "Text", name: "text", widget: "string"}
      - {label: "Local url target", name: "to", widget: "string"}      
      - {label: "List order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}      
      - {label: "Contains sub-menu?", name: "hasSubMenu", widget: "boolean"}      
      - {label: "Image", name: "img", widget: "image", required: false}  
      - {label: "Verb", name: "verb", widget: "string", required: false}  
      - {label: "Title", name: "title", widget: "string", required: false}  
      - label: "Sub Page"
        name: "subPages"
        widget: "list"
        required: false
        fields: 
          - {label: "Subpage Text", name: "subPageText", widget: "string"}  
          - {label: "Subpage url targt", name: "subPageTo", widget: "string"}
  - name: "homePg" 
    label: "Home Page"
    folder: "src/data/homePg"
    create: true
    slug: "{{slug}}"
    identifier_field: pageTitle
    fields:
      - {label: "Page Title", name: "pageTitle", widget: "string"}  
      - {label: "Heading Image", name: "headingImg", widget: "image"}  
      - {label: 'Main text', name: 'body', widget: 'markdown'}  
      - {label: 'Credit text', name: 'creditText', widget: 'string', required: false}
      - {label: 'Background Audio', name: 'bgAudio', widget: 'file', required: false}
      - {label: 'Background Audio Duration', name: 'bgAudioDuration', widget: 'number', valueType: "float", min: 0, required: false}
      - {label: 'Background Audio Fade In Duration', name: 'bgAudioFadeInDuration', widget: 'number', valueType: "float", min: 0, required: false}
      - {label: 'Background Audio Fade Out Duration', name: 'bgAudioFadeOutDuration', widget: 'number', valueType: "float", min: 0, required: false}
      - label: "Slides"
        name: "slides"
        widget: "list"
        fields: 
          - {label: "Image", name: "img", widget: "image"} 
          - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
          - {label: "Opacity (%)", name: "opacity", widget: "number", valueType: "int", min: 0, max: 100}
          - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0, max: 60}
          - {label: "Scale from", name: "scaleFrom", widget: "number", valueType: "float", min: 1, max: 2}
          - {label: "Scale to", name: "scaleTo", widget: "number", valueType: "float", min: 1, max: 2}
          - label: "Pan start from"
            name: "panStart"
            widget: "select"
            options: ["top-left", "top", "top-right", "left", "centre", "right", "bottom-left", "bottom", "bottom-right"]
  - name: "roots&youth"
    label: "Roots & Youth"
    folder: "src/data/roots&youth"
    create: true
    slug: "{{slug}}"
    identifier_field: pageTitle
    fields:
      - {label: "Page Title", name: "pageTitle", widget: "string"}  
      - {label: "Heading Image", name: "headingImg", widget: "image"}  
      - {label: 'Main text', name: 'body', widget: 'markdown', required: false} 
      - label: "Slides"
        name: "slides"
        widget: "list"
        fields: 
          - {label: "Image", name: "img", widget: "image"} 
          - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
          - {label: "Opacity (%)", name: "opacity", widget: "number", valueType: "int", min: 0, max: 100, required: false}
      - {label: "Slide duration (secs)", name: "slideDuration", widget: "number", valueType: "float", min: 0, max: 60, required: false}
      - label: "Videos"
        name: "videos"
        widget: "list"
        fields: 
          - {label: 'Title', name: 'title', widget: 'string', required: false}
          - {label: 'Subtext', name: 'subText', widget: 'markdown', required: false}
          - {label: "Vimeo Url", name: "url", widget: "string"}
          - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}  
          - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
          - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0, required: false}          
      - label: "Full Video"
        name: "fullVideo"
        widget: "object"
        fields:
        - {label: 'Title', name: 'title', widget: 'string', required: false}
        - {label: "Text", name: "text", widget: "string"}
        - {label: "Video File", name: "file", widget: "file", required: false}
        - {label: "Video Url", name: "url", widget: "string", required: false}
        - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image", required: false}        
        - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0, required: false}
  - name: "the-episodes"
    label: "The Episodes"
    folder: "src/data/musical-journey/the-episodes"
    create: true
    slug: "{{slug}}"
    identifier_field: pageTitle
    fields:
      - {label: "Page Title", name: "pageTitle", widget: "string"}
      - {label: "Header Background Image", name: "headerBgImg", widget: "image"}
      - {label: "Title Image", name: "titleImg", widget: "image"}      
      - {label: 'Main text', name: 'body', widget: 'markdown', required: false} 
      - {label: 'Main image', name: 'mainImg', widget: 'image'} 
      - label: "Videos"
        name: "videos"
        widget: "list"
        fields: 
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Short Title', name: 'shortTitle', widget: 'string'}
          - {label: 'Subtext', name: 'subText', widget: 'markdown'}
          - {label: "Vimeo Url", name: "url", widget: "string"}
          - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}  
          - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1}
          - {label: "Duration (secs)", name: "duration", widget: "number", valueType: "float", min: 0}
  - name: "musical-friends"
    label: "Musical Friends"
    folder: "src/data/musical-journey/musical-friends"
    create: true
    slug: "{{slug}}"
    identifier_field: pageTitle
    fields:
      - {label: "Page Title", name: "pageTitle", widget: "string"}
      - {label: "Background Image", name: "backgroundImg", widget: "image"}
      - {label: "Title Image", name: "titleImg", widget: "image"}      
      - {label: 'Main text', name: 'body', widget: 'markdown', required: false}
      - label: "Friends"
        name: "friends"
        widget: "list"
        fields: 
          - {label: 'Name / Title', name: 'name', widget: 'string'}
          - {label: 'Text', name: 'text', widget: 'markdown'}
          - {label: "Link (url)", name: "link", widget: "string"}
          - {label: "Order no.", name: "orderNo", widget: "number", valueType: "int", min: 1} 
          - {label: "Thumbnail Image", name: "thumbnailImg", widget: "image"}
          - {label: "Image Orientation", name: "imgOrientation", widget: "select", options: ["landscape", "portrait"]}
          - label: "Image Position"
            name: "imgPosition"
            widget: "select"
            options: ["top", "bottom", "left", "right"]
          